add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$character
"""

[username]
show_always = true
style_user = "bold green"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold green"
format = "[@$hostname]($style) "

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 3

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_branch]
symbol = " "
style = "bold mauve"

[git_status]
style = "bold yellow"

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
